apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: movies-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/movies-rec-prod/movies-repo/movies-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DATABASE_URL
            - name: GCS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: GCS_BUCKET_NAME
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: IMDB_API_BASE_URL
              value: "https://api.imdbapi.dev"
            - name: SESSION_TTL_SECONDS
              value: "604800"
            - name: MODEL_PATH
              value: "/app/model.pkl"
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ALLOWED_ORIGINS
          resources:
            requests:
              cpu: "300m"
              memory: "1500Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: backend
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: movies-recommendation
data:
  ALLOWED_ORIGINS: "http://34.111.139.77"
